
name: Create Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set LanguageTool version
        run: "echo \"LT_VERSION=$(python -u -c \"import re; print(re.search(r'<lt-version>(.*?)</lt-version>', open('pom.xml', 'r').read()).group(1), end='')\")\" >> $GITHUB_ENV"

      - name: Checkout LanguageTool
        run: git clone --depth 1 --branch v${{ env.LT_VERSION }} https://github.com/languagetool-org/languagetool.git

      - name: Set up Java
        uses: actions/setup-java@v6.0.0
        with:
          java-version: 17
          distribution: temurin

      - name: Build LanguageTool
        working-directory: ./languagetool
        run: ./build.sh languagetool-standalone package -DskipTests

      - name: Create tag
        run: git tag ${{ env.LT_VERSION }} && git push origin ${{ env.LT_VERSION }}

      - name: "Create GitHub Release"
        run: >
          gh release create ${{ env.LT_VERSION }}
          --title='${{ env.LT_VERSION }}'
          --notes='LanguageTool ${{ env.LT_VERSION }} build from https://github.com/languagetool-org/languagetool used for https://github.com/ltex-plus/ltex-ls-plus'
          'languagetool/languagetool-standalone/target/LanguageTool-${{ env.LT_VERSION }}.zip'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  