
name: Pull Request

on:
  pull_request:
    branches:
      - "*"
    paths:
      - pom.xml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set LanguageTool version
        run: "echo \"LT_VERSION=$(python -u -c \"import re; print(re.search(r'<lt-version>(.*?)</lt-version>', open('pom.xml', 'r').read()).group(1), end='')\")\" >> $GITHUB_ENV"

      - name: Checkout LanguageTool
        run: git clone --depth 1 --branch v${{ env.LT_VERSION }} https://github.com/languagetool-org/languagetool.git

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - name: Build LanguageTool
        working-directory: ./languagetool
        run: ./build.sh languagetool-standalone package -DskipTests

  dependabot-merge-create-release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
      actions: write
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'ltex-plus/languagetool-build'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for Dependabot PRs
        if: contains(steps.metadata.outputs.dependency-names, 'languagetool')
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create release
        run: gh workflow run create-release.yml
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
